# Pyber Challenge

### 4.3 Loading and Reading CSV files

In [24]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

# File to Load (Remember to change these)
city_data_to_load = "Resources/city_data.csv"
ride_data_to_load = "Resources/ride_data.csv"

# Read the City and Ride Data
city_data_df = pd.read_csv(city_data_to_load)
ride_data_df = pd.read_csv(ride_data_to_load)

### Merge the DataFrames

In [60]:
# Combine the data into a single dataset
pyber_data_df = pd.merge(ride_data_df, city_data_df, how="left", on=["city", "city"])

# Display the data table for preview
pyber_data_df.head()

,city,date,fare,ride_id,driver_count,type
0,Lake Jonathanshire,2019-01-14 10:14:22,13.83,5739410935873,5,Urban
1,South Michelleport,2019-03-04 18:24:09,30.24,2343912425577,72,Urban
2,Port Samanthamouth,2019-02-24 04:29:00,33.44,2005065760003,57,Urban
3,Rodneyfort,2019-02-10 23:22:03,23.44,5149245426178,34,Urban
4,South Jack,2019-03-06 04:28:35,34.58,3908451377344,46,Urban

## Deliverable 1: Get a Summary DataFrame

In [28]:
#  1. Get the total rides for each city type
# Create the urban city dataframe
urban_cities_df = pyber_data_df[pyber_data_df["type"] == "Urban"]
urban_cities_df

,city,date,fare,ride_id,driver_count,type
0,Lake Jonathanshire,2019-01-14 10:14:22,13.83,5739410935873,5,Urban
1,South Michelleport,2019-03-04 18:24:09,30.24,2343912425577,72,Urban
2,Port Samanthamouth,2019-02-24 04:29:00,33.44,2005065760003,57,Urban
3,Rodneyfort,2019-02-10 23:22:03,23.44,5149245426178,34,Urban
4,South Jack,2019-03-06 04:28:35,34.58,3908451377344,46,Urban
5,South Latoya,2019-03-11 12:26:48,9.52,1994999424437,10,Urban
6,New Paulville,2019-02-27 11:17:56,43.25,793208410091,44,Urban
7,Simpsonburgh,2019-04-26 00:43:24,35.98,111953927754,21,Urban
8,South Karenland,2019-01-08 03:28:48,35.09,7995623208694,4,Urban
9,North Jasmine,2019-03-09 06:26:29,42.81,5327642267789,33,Urban
10,New Kimberlyborough,2019-02-07 01:10:11,9.34,7992781920789,33,Urban
11,West Angela,2019-01-12 01:45:27,26.86,4820052223501,48,Urban
12,Rodneyfort,2019-03-02 18:03:20,44.26,2494064867705,34,Urban
13,West Angela,2019-01-10 12:17:31,12.74,2108723916092,48,Urban
14,Roberthaven,2019-05-04 14:48:56,25.66,1026197778354,47,Urban
15,North Jason,2019-03-28 22:28:44,9.19,7007022521141,6,Urban
16,Williamsview,2019-01-03 16:19:25,18.93,1979492913169,46,Urban
17,Leahton,2019-02-26 18:42:15,8.85,6966668662612,17,Urban
18,West Anthony,2019-03-06 02:27:01,10.02,9396763280782,70,Urban
19,New Kimberlyborough,2019-04-25 22:58:38,29.67,4823568522144,33,Urban
20,Roberthaven,2019-02-24 10:26:34,7.80,2180566685151,47,Urban
21,New Paulton,2019-05-01 03:12:49,8.28,8527101897862,44,Urban
22,West Patrickchester,2019-03-19 05:46:20,40.86,898889456779,25,Urban
23,Deanville,2019-04-25 03:29:09,41.52,6055928921559,49,Urban
24,West Josephberg,2019-02-19 16:22:09,36.39,3322126516683,45,Urban
25,West Samuelburgh,2019-05-03 14:33:41,41.12,7330842806458,73,Urban
26,West Heidi,2019-03-14 23:46:50,24.40,4908573010166,28,Urban
27,Loganberg,2019-04-01 01:06:03,8.23,678728883160,23,Urban
28,Huntermouth,2019-02-10 23:32:13,25.79,1880379662035,37,Urban
29,South Latoya,2019-01-11 18:44:14,27.41,8662301917375,10,Urban
...,...,...,...,...,...,...
1595,West Gabriel,2019-02-20 09:30:53,28.13,7467212471692,57,Urban
1596,Carriemouth,2019-03-25 21:25:47,26.40,4293523822822,52,Urban
1597,Huntermouth,2019-03-17 15:43:09,30.31,6909760173471,37,Urban
1598,Valentineton,2019-01-12 05:52:15,42.31,5901460118661,45,Urban
1599,East Kaylahaven,2019-01-29 06:40:02,26.79,5038187912880,65,Urban
1600,Lake Danielberg,2019-04-12 05:18:16,41.45,5338695664074,19,Urban
1601,West Robert,2019-01-15 08:14:17,33.91,2161158839398,39,Urban
1602,Williamsstad,2019-04-04 06:55:13,31.52,778427079687,59,Urban
1603,Port David,2019-04-22 23:30:50,30.03,7355586586718,7,Urban
1604,Karenside,2019-03-03 18:15:32,19.19,1723489219600,5,Urban
1605,Valentineton,2019-03-16 23:59:11,5.23,7407814114542,45,Urban
1606,New Kimberlyborough,2019-04-03 03:36:16,43.07,5603777741586,33,Urban
1607,New Jacobville,2019-04-20 05:31:08,13.35,9259173509501,50,Urban
1608,Joneschester,2019-04-13 18:44:13,27.36,7530382780656,39,Urban
1609,Joneschester,2019-04-20 09:40:03,30.12,8972497663155,39,Urban
1610,Jerryton,2019-03-24 12:17:30,31.47,5424245579315,64,Urban
1611,Grahamburgh,2019-01-03 15:37:24,17.61,7877228075348,61,Urban
1612,Royland,2019-01-18 00:03:01,32.11,4548837819274,64,Urban
1613,West Robert,2019-03-10 20:00:35,6.74,6675182507896,39,Urban
1614,Karenside,2019-02-19 20:56:59,17.41,1217247793421,5,Urban
1615,Williamsview,2019-04-18 02:07:15,39.79,8745531941706,46,Urban
1616,Simpsonburgh,2019-03-03 08:45:54,7.63,4176780124147,21,Urban
1617,West Angela,2019-05-07 01:03:12,12.35,2050512349119,48,Urban
1618,West Heidi,2019-01-15 11:49:40,21.44,83498621902,28,Urban
1619,Leahton,2019-03-13 09:17:41,36.79,6214133326256,17,Urban
1620,Reynoldsfurt,2019-02-14 11:25:10,39.40,9070692324754,67,Urban
1621,Christopherfurt,2019-03-13 01:47:52,32.05,2788817929605,41,Urban
1622,Raymondhaven,2019-03-20 02:20:34,38.53,8658255136559,11,Urban
1623,Port Johnbury,2019-03-26 07:22:45,7.63,8089282605778,3,Urban
1624,West Gabriel,2019-05-05 01:24:06,27.57,4428773411209,57,Urban

In [29]:
# Get the number of rides for urban cities.
urban_ride_count = urban_cities_df.groupby(["city"]).count()["ride_id"]
urban_ride_count

city
Amandaburgh             18
Barajasview             22
Carriemouth             27
Christopherfurt         27
Deanville               19
East Kaylahaven         29
Erikaland               12
Grahamburgh             25
Huntermouth             24
Hurleymouth             28
Jerryton                25
Johnton                 21
Joneschester            25
Justinberg              30
Karenberg               17
Karenside               28
Lake Danielberg         26
Lake Jonathanshire      24
Lake Scottton           24
Leahton                 21
Liumouth                33
Loganberg               28
Martinezhaven           24
New Jacobville          18
New Kimberlyborough     30
New Paulton             19
New Paulville           22
North Barbara           22
North Jasmine           30
North Jason             35
                        ..
Port Johnbury           22
Port Samanthamouth      25
Raymondhaven            25
Reynoldsfurt            19
Richardfort             28
Roberthaven             24
Robertport              20
Rodneyfort              23
Rogerston               22
Royland                 30
Simpsonburgh            24
South Evanton           31
South Jack              19
South Karenland         38
South Latoya            19
South Michelleport      31
South Phillip           31
Valentineton            22
West Angela             39
West Anthony            30
West Christopherberg    26
West Ericstad           18
West Gabriel            23
West Heidi              28
West Josephberg         26
West Patrickchester     16
West Robert             31
West Samuelburgh        25
Williamsstad            23
Williamsview            20
Name: ride_id, Length: 66, dtype: int64

In [63]:
# Create the Suburban city DataFrames.
suburban_cities_df = pyber_data_df[pyber_data_df["type"] == "Suburban"]
suburban_cities_df

,city,date,fare,ride_id,driver_count,type
1625,Barronchester,2019-01-27 03:08:01,27.79,6653622887913,11,Suburban
1626,East Kentstad,2019-04-07 19:44:19,18.75,6575961095852,20,Suburban
1627,Lake Omar,2019-01-17 21:33:35,21.71,966911700371,22,Suburban
1628,Myersshire,2019-02-27 17:38:39,17.10,5706770909868,19,Suburban
1629,West Hannah,2019-04-19 01:06:59,37.78,2273047151891,12,Suburban
1630,East Marymouth,2019-03-29 08:36:20,37.60,6370863861570,5,Suburban
1631,New Raymond,2019-02-25 21:40:18,20.44,5984505117874,17,Suburban
1632,Lake Robertside,2019-01-11 20:17:36,46.51,6574333011308,4,Suburban
1633,Josephside,2019-03-30 09:45:11,44.74,5592692102803,25,Suburban
1634,Brandonfort,2019-01-14 12:35:27,28.02,8100258078935,10,Suburban
1635,Josephside,2019-02-07 06:56:45,31.94,3185694946333,25,Suburban
1636,New Raymond,2019-03-21 01:45:29,22.12,6031755734913,17,Suburban
1637,Lewisland,2019-02-14 17:38:17,42.31,580385794188,4,Suburban
1638,East Kentstad,2019-01-22 20:43:30,35.01,8750865857333,20,Suburban
1639,Myersshire,2019-04-29 06:08:03,17.99,1127095356276,19,Suburban
1640,Myersshire,2019-01-10 06:32:04,45.81,7014255933887,19,Suburban
1641,Lewisland,2019-01-30 15:08:13,32.40,5099208436594,4,Suburban
1642,West Hannah,2019-03-22 20:18:32,25.86,7624914034208,12,Suburban
1643,North Richardhaven,2019-02-18 10:21:39,41.54,4267383307027,1,Suburban
1644,New Olivia,2019-03-29 02:52:48,44.12,7724469578438,20,Suburban
1645,New Shannonberg,2019-03-19 08:13:37,25.46,374752841670,20,Suburban
1646,Barronchester,2019-05-05 04:03:11,30.38,2281522828169,11,Suburban
1647,Nicolechester,2019-02-09 12:26:03,40.83,85473064902,19,Suburban
1648,New Raymond,2019-03-18 12:07:10,36.26,3151412877753,17,Suburban
1649,New Raymond,2019-05-03 12:23:37,48.56,9495029351539,17,Suburban
1650,Victoriaport,2019-04-21 15:21:47,12.13,3313120309203,16,Suburban
1651,South Teresa,2019-01-29 12:51:02,38.47,5746182119035,21,Suburban
1652,North Richardhaven,2019-04-07 00:32:23,36.32,5014291527509,1,Suburban
1653,East Aaronbury,2019-03-19 10:43:53,20.04,4117474421029,7,Suburban
1654,South Teresa,2019-02-23 04:35:04,46.02,4623132352357,21,Suburban
...,...,...,...,...,...,...
2220,Lake Robertside,2019-02-12 09:45:02,20.03,9626340588797,4,Suburban
2221,South Brenda,2019-03-19 19:25:49,48.98,8685637991901,1,Suburban
2222,Josephside,2019-04-24 10:29:15,42.58,1067620076654,25,Suburban
2223,West Kimmouth,2019-03-05 22:04:15,48.20,321833677,4,Suburban
2224,Barronchester,2019-04-05 14:12:55,33.50,91435348621,11,Suburban
2225,Bethanyland,2019-03-06 10:01:58,13.86,8571759718178,22,Suburban
2226,Lake Omar,2019-02-20 21:56:22,33.61,2721355482706,22,Suburban
2227,Williamsonville,2019-04-28 19:35:03,16.96,9631291999264,2,Suburban
2228,Colemanland,2019-01-19 15:24:42,24.40,6652560250346,23,Suburban
2229,Port Shane,2019-01-30 20:43:57,49.52,8262792633558,7,Suburban
2230,West Kimmouth,2019-03-13 14:50:48,18.72,9388333400065,4,Suburban
2231,Nicolechester,2019-05-05 08:45:58,15.43,8496653987287,19,Suburban
2232,Mezachester,2019-04-19 19:05:10,29.12,8894988518709,14,Suburban
2233,New Olivia,2019-03-27 09:35:08,34.54,4642968219429,20,Suburban
2234,East Danielview,2019-01-25 11:58:33,48.32,1831668503737,22,Suburban
2235,Brandonfort,2019-04-15 04:12:53,47.17,7388012906675,10,Suburban
2236,Port Shane,2019-04-03 22:33:51,15.59,127445516863,7,Suburban
2237,Colemanland,2019-05-04 04:24:31,12.62,4902707063158,23,Suburban
2238,South Teresa,2019-03-05 19:18:37,32.29,4981692995989,21,Suburban
2239,South Brenda,2019-04-25 07:08:25,23.60,1784015692342,1,Suburban
2240,East Aaronbury,2019-04-11 03:24:14,34.40,6540905865488,7,Suburban
2241,Sotoville,2019-03-13 16:06:10,14.36,8629533024103,10,Suburban
2242,West Hannah,2019-01-21 19:54:08,41.95,16507766547,12,Suburban
2243,South Teresa,2019-03-09 09:54:33,25.08,8136313906059,21,Suburban
2244,Bethanyland,2019-04-02 04:29:09,34.38,1783847934910,22,Suburban
2245,West Hannah,2019-03-02 17:06:03,13.92,7388937249208,12,Suburban
2246,Lake Robertside,2019-04-03 03:27:45,12.76,1301757653884,4,Suburban
2247,Colemanland,2019-01-10 06:49:58,27.70,8704067171414,23,Suburban
2248,East Marymouth,2019-02-12 23:18:53,47.41,7409660239158,5,Suburban
2249,New Raymond,2019-02-11 17:28:27,17.97,7551674475043,17,Suburban

In [33]:
# Get the number of rides for suburban cities.
suburban_ride_count = suburban_cities_df.groupby(["city"]).count()["ride_id"]
suburban_ride_count

city
Barronchester    16
Bethanyland      18
Brandonfort      19
Colemanland      22
Davidfurt        17
Name: ride_id, dtype: int64

In [64]:
# Create the Rural city DataFrames.
rural_cities_df = pyber_data_df[pyber_data_df["type"] == "Rural"]
rural_cities_df

,city,date,fare,ride_id,driver_count,type
2250,Randallchester,2019-04-13 11:13:31,43.22,1076079536213,9,Rural
2251,North Holly,2019-02-02 14:54:00,12.42,1985256326182,8,Rural
2252,Michaelberg,2019-03-27 18:27:34,54.85,4421836952718,6,Rural
2253,Lake Latoyabury,2019-02-23 21:12:24,47.90,3269652929887,2,Rural
2254,Lake Latoyabury,2019-05-06 08:57:56,51.80,4018025271936,2,Rural
2255,Taylorhaven,2019-04-06 01:01:29,45.31,2275364435623,1,Rural
2256,Garzaport,2019-02-18 18:27:48,36.16,2928337561347,7,Rural
2257,New Ryantown,2019-01-27 17:33:41,42.68,7994603753131,2,Rural
2258,Lake Latoyabury,2019-04-02 21:00:22,13.46,8232864757802,2,Rural
2259,North Holly,2019-02-16 17:02:51,39.46,4571476032148,8,Rural
2260,Bradshawfurt,2019-03-06 21:44:53,19.74,6080367372860,7,Rural
2261,South Marychester,2019-02-19 00:23:09,32.72,1481751072369,1,Rural
2262,Bradshawfurt,2019-03-24 18:53:18,57.51,2301998876294,7,Rural
2263,Lake Latoyabury,2019-01-22 12:42:55,13.50,8493335787500,2,Rural
2264,South Marychester,2019-01-02 11:18:32,52.12,3454018971635,1,Rural
2265,Jessicaport,2019-01-01 09:45:36,43.69,2424875833354,1,Rural
2266,South Jennifer,2019-04-01 09:32:45,21.63,9135979586871,7,Rural
2267,South Marychester,2019-02-21 19:16:48,55.40,8822356392057,1,Rural
2268,South Saramouth,2019-02-20 16:32:36,44.29,3622365199969,7,Rural
2269,Lake Latoyabury,2019-04-22 16:56:46,38.46,1671918742352,2,Rural
2270,Lake Jamie,2019-03-13 06:41:49,26.09,1599158550738,4,Rural
2271,Newtonview,2019-01-08 06:19:45,19.39,5350347217506,1,Rural
2272,Michaelberg,2019-01-18 00:46:28,15.12,1031697508349,6,Rural
2273,Jessicaport,2019-01-14 07:09:17,18.05,5405362355006,1,Rural
2274,South Marychester,2019-01-15 21:44:26,30.26,3837056996776,1,Rural
2275,North Jaime,2019-03-06 09:09:23,44.17,1152195873170,1,Rural
2276,Penaborough,2019-02-24 00:44:00,21.89,2069309881916,6,Rural
2277,North Jaime,2019-03-12 13:05:56,23.21,5987447089759,1,Rural
2278,Lake Latoyabury,2019-04-16 21:12:48,24.10,4896030744313,2,Rural
2279,South Jennifer,2019-03-07 19:10:13,48.79,9730627367446,7,Rural
...,...,...,...,...,...,...
2345,West Heather,2019-02-04 16:29:23,13.97,7118893881453,4,Rural
2346,West Heather,2019-04-18 19:33:12,46.60,3671003215967,4,Rural
2347,West Heather,2019-03-02 21:04:10,20.99,5766454453070,4,Rural
2348,South Saramouth,2019-01-28 15:55:33,31.25,7118046558393,7,Rural
2349,West Heather,2019-03-06 20:06:51,48.11,2570548892682,4,Rural
2350,Garzaport,2019-05-06 16:57:16,18.90,8826696981094,7,Rural
2351,South Saramouth,2019-03-27 21:07:16,11.87,170351888128,7,Rural
2352,Randallchester,2019-04-07 23:42:07,10.79,1615474447641,9,Rural
2353,Harringtonfort,2019-01-09 15:30:35,31.84,3730685356921,4,Rural
2354,South Saramouth,2019-04-12 18:11:50,57.23,5081198789583,7,Rural
2355,North Holly,2019-01-03 19:51:01,19.90,5559509612597,8,Rural
2356,New Ryantown,2019-05-05 19:29:38,26.53,2302209966018,2,Rural
2357,West Heather,2019-02-02 06:28:04,53.07,2462950442268,4,Rural
2358,Lake Latoyabury,2019-02-25 04:10:19,16.18,8492924830016,2,Rural
2359,South Marychester,2019-01-19 11:40:46,49.44,90058815985,1,Rural
2360,Jessicaport,2019-01-31 17:57:25,58.29,623154556195,1,Rural
2361,Michaelberg,2019-03-22 22:20:54,38.30,8032727406577,6,Rural
2362,North Holly,2019-04-18 19:26:25,30.94,3441061016826,8,Rural
2363,Michaelberg,2019-03-13 14:40:18,37.72,8842606115175,6,Rural
2364,Lake Jamie,2019-02-25 23:46:02,28.65,5815763839331,4,Rural
2365,Lake Jamie,2019-04-19 04:32:47,16.29,3518682119233,4,Rural
2366,North Holly,2019-03-18 10:38:05,40.34,3787775176860,8,Rural
2367,Michaelberg,2019-01-27 18:43:05,38.42,862622008020,6,Rural
2368,Lake Jamie,2019-04-29 01:58:44,54.22,2489264790267,4,Rural
2369,Bradshawfurt,2019-01-30 10:55:23,51.39,1328274868072,7,Rural
2370,Michaelberg,2019-04-29 17:04:39,13.38,8550365057598,6,Rural
2371,Lake Latoyabury,2019-01-30 00:05:47,20.76,9018727594352,2,Rural
2372,North Jaime,2019-02-10 21:03:50,11.11,2781339863778,1,Rural
2373,West Heather,2019-05-07 19:22:15,44.94,4256853490277,4,Rural
2374,Newtonview,2019-04-25 10:20:13,55.84,9990581345298,1,Rural

In [37]:
# Get the number of rides for rural cities.
rural_ride_count = rural_cities_df.groupby(["city"]).count()["ride_id"]
rural_ride_count.head()

city
Bradshawfurt      10
Garzaport          3
Harringtonfort     6
Jessicaport        6
Lake Jamie         6
Name: ride_id, dtype: int64

In [66]:
# 2. Get the total drivers for each city type
# Get the number of drivers for urban cities
urban_ride_sum = urban_cities_df.groupby(["city"]).sum()["driver_count"]
urban_ride_sum.head(10)

city
Amandaburgh         216
Barajasview         572
Carriemouth        1404
Christopherfurt    1107
Deanville           931
East Kaylahaven    1885
Erikaland           444
Grahamburgh        1525
Huntermouth         888
Hurleymouth        1008
Name: driver_count, dtype: int64

In [53]:
# Get the number of drivers for suburban cities.
suburban_ride_sum = suburban_cities_df.groupby(["city"]).sum()["driver_count"]
suburban_ride_sum.head(10)

city
Barronchester      176
Bethanyland        396
Brandonfort        190
Colemanland        506
Davidfurt          391
East Aaronbury      63
East Danielview    374
East Kentstad      260
East Marymouth     135
Grayville           30
Name: driver_count, dtype: int64

In [68]:
# Get the number of drivers for rural cities.
rural_ride_sum = rural_cities_df.groupby(["city"]).sum()["driver_count"]
rural_ride_sum.head()

city
Bradshawfurt      70
Garzaport         21
Harringtonfort    24
Jessicaport        6
Lake Jamie        24
Name: driver_count, dtype: int64

In [5]:
#  3. Get the total amount of fares for each city type

In [6]:
#  4. Get the average fare per ride for each city type.

In [7]:
# 5. Get the average fare per driver for each city type.

In [8]:
#  6. Create a PyBer summary DataFrame.

In [9]:
#  7. Cleaning up the DataFrame. Delete the index name
pyber_summary_df.index.name = None

In [10]:
#  8. Format the columns.

## Deliverable 2.  Create a multiple line plot that shows the total weekly of the fares for each type of city.

In [11]:
# 1. Read the merged DataFrame

In [12]:
# 2. Using groupby() to create a new DataFrame showing the sum of the fares 
#  for each date where the indices are the city type and date.

In [13]:
# 3. Reset the index on the DataFrame you created in #1. This is needed to use the 'pivot()' function.
# df = df.reset_index()

In [14]:
# 4. Create a pivot table with the 'date' as the index, the columns ='type', and values='fare' 
# to get the total fares for each type of city by the date.

In [15]:
# 5. Create a new DataFrame from the pivot table DataFrame using loc on the given dates, '2019-01-01':'2019-04-29'.

In [16]:
# 6. Set the "date" index to datetime datatype. This is necessary to use the resample() method in Step 8.
# df.index = pd.to_datetime(df.index)

In [17]:
# 7. Check that the datatype for the index is datetime using df.info()

In [18]:
# 8. Create a new DataFrame using the "resample()" function by week 'W' and get the sum of the fares for each week.

In [19]:
# 8. Using the object-oriented interface method, plot the resample DataFrame using the df.plot() function. 

# Import the style from Matplotlib.
from matplotlib import style
# Use the graph style fivethirtyeight.
style.use('fivethirtyeight')